# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Version updater

on:
  issues:
    types: [opened]

jobs:

  dispatch_test:
    if: github.event.issue.title == 'Dispatch Test'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      workingd: run_tests
    - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: ${{env.workingd}}
        id: node_step
        run: npm install
      - run: npm run run_tests

  new_version:
    if: github.event.issue.title == 'New Version'
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.execute.outputs.branch_name }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      workingd: new_version
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: ${{env.workingd}}
        id: node_step
        run: npm install
      - run: npm run build_version
        working-directory: ${{env.workingd}}
        id: execute
      - name: cancelling
        if: ${{steps.execute.outputs.cancelled == 'true'}}
        uses: andymckay/cancel-action@0.2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{steps.execute.outputs.branch_name}}
          title: "Closes #${{steps.execute.outputs.issue_number}} , Adds version ${{steps.execute.outputs.version}} for player ${{steps.execute.outputs.player}}" 

  new_player:
      if: github.event.issue.title == 'New Player'
      runs-on: ubuntu-latest
      outputs:
        branch_name: ${{ steps.execute.outputs.branch_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        workingd: new_player
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '14.x'
        - name: Install dependencies
          working-directory: ${{env.workingd}}
          id: node_step
          run: npm install
        - run: npm run build
          working-directory: ${{env.workingd}}
          id: execute
        - name: cancelling
          if: ${{steps.execute.outputs.cancelled == 'true'}}
          uses: andymckay/cancel-action@0.2
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            branch: ${{steps.execute.outputs.branch_name}}
            title: "Closes #${{steps.execute.outputs.issue_number}} , Adds player ${{steps.execute.outputs.player}} with version ${{steps.execute.outputs.version}}" 

  new_feature:
    if: github.event.issue.title == 'New Feature'
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.execute.outputs.branch_name }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      workingd: new_feature
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: ${{env.workingd}}
        id: node_step
        run: npm install
      - run: npm run build
        working-directory: ${{env.workingd}}
        id: execute
      - name: cancelling
        if: ${{steps.execute.outputs.cancelled == 'true'}}
        uses: andymckay/cancel-action@0.2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{steps.execute.outputs.branch_name}}
          title: "Closes #${{steps.execute.outputs.issue_number}} , Creates new feature ${{steps.execute.outputs.feature_title}}" 
