# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ player_version ]
  pull_request:
    branches: [ player_version ]

jobs:

  create_snapshots:
  
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      G_SECRET: ${{ secrets.G_SECRET }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ../images
    steps:
    - uses: actions/setup-node@v2
    - run: npm run execute
