# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ player_version ]
  pull_request:
    branches: [ player_version ]
  issues:
    types: [opened, edited]

outputs:
  branch_name: # id of output
    description: 'The branch name'

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - uses: peterjgrainger/action-create-branch@v2.0.1
      #   with:
      #     branch: 'release-notes'
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        id: 'nodestep'
        run: npm install
      - run: npm run execute
      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{outputs.branch_name}}
