# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ player_version ]

jobs:

  create_pull_request:
  
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    defaults:
      run:
        working-directory: ./images
    steps:
    - uses: actions/setup-node@v2
    
    - run: npm run execute
