# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  issues:
    types: [opened, edited]

jobs:

  build:
    if: github.event.issue.title == 'new issue'
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.execute.outputs.branch_name }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - uses: peterjgrainger/action-create-branch@v2.0.1
      #   with:
      #     branch: 'release-notes'
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        id: node_step
        run: npm install
      - run: npm run execute_ts
        id: execute
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     new_branch: ${{steps.execute.outputs.branch_name}}
      - name: cancelling
        if: ${{steps.execute.outputs.cancelled == 'true'}}
        uses: andymckay/cancel-action@0.2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{steps.execute.outputs.branch_name}}
          title: "Closes #${{steps.execute.outputs.issue_number}} , Adds version ${{steps.execute.outputs.version}} for player ${{steps.execute.outputs.player}}" 

  build2:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hellooo"
      - id: step2
        run: echo "worldddd"
      - id: step3
        run: echo "title is ${{github.event.issue.title}}"
      - id: step4
        run: echo "lowercase is ${{github.event.issue.title.lowercase}}"
      - name: Install dependencies
        working-directory: new_version
        id: node_step
        run: npm install
      - run: npm run execute_ts
        id: in_directory
      - id: step5
        run: echo "lowercase is ${{steps.in_directory.outputs.the_value}}"