# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, schema_validator, gold_integration ]
  pull_request:
    branches: [ main, schema_validator, gold_integration ]

jobs:

  create_snapshots:
  
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      G_SECRET: ${{ secrets.G_SECRET }}
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ./images
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-go@v2
    #   with:
    #     go-version: '^1.16.4' # The Go version to download (if necessary) and use.
    # - run: go get go.skia.org/infra/gold-client/cmd/goldctl
    ## - run: go run hello.go
    - uses: actions/setup-node@v2
    - run: npm run execute
    - name: print secrets
      run: |
          echo $G_SECRET >> ./test_env.txt
      shell: bash
